import type { components } from './schema'

export type Schemas = components['schemas']

export type CurrentUser = Schemas['CurrentUser']
export type UserRole = Schemas['UserRole']
export type AuthLoginRequest = Schemas['AuthLoginRequest']
export type AuthTokenResponse = Schemas['AuthTokenResponse']
export type StudentProfile = Schemas['StudentProfile']
export type AcademicProfile = Schemas['AcademicProfile']
export type RuleEvaluationResult = Schemas['RuleEvaluationResult']
export type RuleEvaluationRequest = Schemas['RuleEvaluationRequest']
export type RequirementRule = Schemas['RequirementRule']
export type RequirementRuleInput = Schemas['RequirementRuleInput']
export type Project = Schemas['Project']
export type ProjectInput = Schemas['ProjectInput']
export type ProjectPatch = Schemas['ProjectPatch']
export type ProjectStatus = Schemas['ProjectStatus']
export type ProjectSourceType = Schemas['ProjectSourceType']
export type ProjectApplication = Schemas['ProjectApplication']
export type ApplicationInput = Schemas['ApplicationInput']
export type ApplicationStatus = Schemas['ApplicationStatus']
export type Assignment = Schemas['Assignment']
export type HourLog = Schemas['HourLog']
export type HourLogInput = Schemas['HourLogInput']
export type ApprovalStatus = Schemas['ApprovalStatus']
export type DocumentRequirement = Schemas['DocumentRequirement']
export type DocumentRequirementInput = Schemas['DocumentRequirementInput']
export type DocumentRequirementPatch = Schemas['DocumentRequirementPatch']
export type DocumentUpload = Schemas['DocumentUpload']
export type DocumentUploadInput = Schemas['DocumentUploadInput']
export type Certificate = Schemas['Certificate']
export type ProgressReport = Schemas['ProgressReport']
export type ProjectReport = Schemas['ProjectReport']
export type Company = Schemas['Company']
export type CompanyInput = Schemas['CompanyInput']
export type CompanyPatch = Schemas['CompanyPatch']


