/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HourLogsRouteImport } from './routes/hour-logs'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsJobSearchRouteImport } from './routes/projects/job-search'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdEditRouteImport } from './routes/projects/$projectId/edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HourLogsRoute = HourLogsRouteImport.update({
  id: '/hour-logs',
  path: '/hour-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsJobSearchRoute = ProjectsJobSearchRouteImport.update({
  id: '/projects/job-search',
  path: '/projects/job-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdEditRoute = ProjectsProjectIdEditRouteImport.update({
  id: '/projects/$projectId/edit',
  path: '/projects/$projectId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/applications': typeof ApplicationsRoute
  '/assignments': typeof AssignmentsRoute
  '/certificates': typeof CertificatesRoute
  '/companies': typeof CompaniesRoute
  '/documents': typeof DocumentsRoute
  '/hour-logs': typeof HourLogsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/setup': typeof SetupRoute
  '/projects/job-search': typeof ProjectsJobSearchRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/applications': typeof ApplicationsRoute
  '/assignments': typeof AssignmentsRoute
  '/certificates': typeof CertificatesRoute
  '/companies': typeof CompaniesRoute
  '/documents': typeof DocumentsRoute
  '/hour-logs': typeof HourLogsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/setup': typeof SetupRoute
  '/projects/job-search': typeof ProjectsJobSearchRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/applications': typeof ApplicationsRoute
  '/assignments': typeof AssignmentsRoute
  '/certificates': typeof CertificatesRoute
  '/companies': typeof CompaniesRoute
  '/documents': typeof DocumentsRoute
  '/hour-logs': typeof HourLogsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/setup': typeof SetupRoute
  '/projects/job-search': typeof ProjectsJobSearchRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/applications'
    | '/assignments'
    | '/certificates'
    | '/companies'
    | '/documents'
    | '/hour-logs'
    | '/login'
    | '/profile'
    | '/reports'
    | '/rules'
    | '/setup'
    | '/projects/job-search'
    | '/projects/new'
    | '/projects/'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/applications'
    | '/assignments'
    | '/certificates'
    | '/companies'
    | '/documents'
    | '/hour-logs'
    | '/login'
    | '/profile'
    | '/reports'
    | '/rules'
    | '/setup'
    | '/projects/job-search'
    | '/projects/new'
    | '/projects'
    | '/projects/$projectId/edit'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/applications'
    | '/assignments'
    | '/certificates'
    | '/companies'
    | '/documents'
    | '/hour-logs'
    | '/login'
    | '/profile'
    | '/reports'
    | '/rules'
    | '/setup'
    | '/projects/job-search'
    | '/projects/new'
    | '/projects/'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AssignmentsRoute: typeof AssignmentsRoute
  CertificatesRoute: typeof CertificatesRoute
  CompaniesRoute: typeof CompaniesRoute
  DocumentsRoute: typeof DocumentsRoute
  HourLogsRoute: typeof HourLogsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  RulesRoute: typeof RulesRoute
  SetupRoute: typeof SetupRoute
  ProjectsJobSearchRoute: typeof ProjectsJobSearchRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdEditRoute: typeof ProjectsProjectIdEditRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hour-logs': {
      id: '/hour-logs'
      path: '/hour-logs'
      fullPath: '/hour-logs'
      preLoaderRoute: typeof HourLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/job-search': {
      id: '/projects/job-search'
      path: '/projects/job-search'
      fullPath: '/projects/job-search'
      preLoaderRoute: typeof ProjectsJobSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/edit': {
      id: '/projects/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof ProjectsProjectIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApplicationsRoute: ApplicationsRoute,
  AssignmentsRoute: AssignmentsRoute,
  CertificatesRoute: CertificatesRoute,
  CompaniesRoute: CompaniesRoute,
  DocumentsRoute: DocumentsRoute,
  HourLogsRoute: HourLogsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  RulesRoute: RulesRoute,
  SetupRoute: SetupRoute,
  ProjectsJobSearchRoute: ProjectsJobSearchRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdEditRoute: ProjectsProjectIdEditRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
